services:
  postgres:
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data:/data
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - benchmark

  pgadmin:
    image: dpage/pgadmin4:8.12.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 15432
    ports:
      - 8002:15432
    networks:
      - benchmark
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:

networks:
  benchmark:
    external: true