services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.15
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    networks:
      - benchmark
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2024-08-29T01-40-52Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - benchmark
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server /data --console-address ":9001"

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.10  
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
    networks:
      - benchmark
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "etcd"
      - "minio"

  backup:
    container_name: milvus-backup
    image: milvusdb/milvus-backup
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/backup:/app/backup
      - ${DOCKER_VOLUME_DIRECTORY:-.}/backup.yaml:/app/configs/backup.yaml
    ports:
     - "8888:8888"
    networks:
      - benchmark
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "etcd"
      - "minio"
      - "standalone"
    command: ./milvus-backup server -p 8888

  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.4.8
    ports:
      - "8001:3000"
    networks:
      - benchmark
    depends_on:
      - "etcd"
      - "minio"
      - "standalone"

networks:
  benchmark:
    external: true
